import { promises as fs } from "node:fs";
import { join } from "node:path";
import { README_FILE } from "@shared/constants";
import type { IndexSnapshot } from "@shared/types";

/**
 * The vault's table of contents, regenerated into every commit that changes the set of
 * documents. It exists so the repo reads as something on github.com and not only in the
 * app — which is also why it is committed rather than gitignored.
 */
export function renderReadme(snap: IndexSnapshot): string {
  const lines = [
    "# Vault",
    "",
    `${snap.docs.length} documents · generated by Vault, do not edit by hand.`,
    "",
  ];
  for (const p of snap.projects) {
    lines.push(`## ${p.name} (${p.count})`, "");
    for (const d of snap.docs.filter((x) => x.projectSlug === p.slug)) {
      const tags = d.tags.length ? " · " + d.tags.map((t) => "#" + t).join(" ") : "";
      lines.push(`- [${d.title}](${encodeURI(d.path)}) — ${d.created.slice(0, 10)}${tags}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

export async function writeReadme(root: string, snap: IndexSnapshot): Promise<void> {
  await fs.writeFile(join(root, README_FILE), renderReadme(snap));
}
