import { promises as fs } from "node:fs";
import { join } from "node:path";
import { README_FILE } from "@shared/constants";
import type { IndexSnapshot } from "@shared/types";
import type { VaultContext } from "./vault.types";

/**
 * The vault's table of contents, regenerated into every commit that changes the set of
 * documents. It exists so the repo reads as something on github.com and not only in the
 * app — which is also why it is committed rather than gitignored.
 */
export function renderReadme(snap: IndexSnapshot): string {
  const lines = [
    "# Vault",
    "",
    `${snap.docs.length} documents · generated by Marasca, do not edit by hand.`,
    "",
  ];
  for (const p of snap.projects) {
    lines.push(`## ${p.name} (${p.count})`, "");
    for (const d of snap.docs.filter((x) => x.projectSlug === p.slug)) {
      const tags = d.tags.length ? " · " + d.tags.map((t) => "#" + t).join(" ") : "";
      lines.push(`- [${d.title}](${encodeURI(d.path)}) — ${d.created.slice(0, 10)}${tags}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

export async function writeReadme(root: string, snap: IndexSnapshot): Promise<void> {
  await fs.writeFile(join(root, README_FILE), renderReadme(snap));
}

/**
 * The shape every change to the set of documents takes: commit the change, regenerate
 * the index, and fold it into that same commit. Written out three times before this,
 * and the README was the thing left behind when one of them was edited.
 */
export async function commitWithReadme(
  ctx: VaultContext,
  paths: string[],
  message: string,
): Promise<boolean> {
  // Nothing staged makes no commit and an empty sha. Amending then would rewrite the
  // commit before it — often one already on GitHub, so the next push is rejected.
  if (!(await ctx.git.commitPaths(paths, message))) return false;
  await ctx.writeReadme();
  await ctx.git.amendPaths([README_FILE]);

  return true;
}
