import type { EventChannel, InvokeChannel } from "./ipc.types";

/** Allow-list enforced by the preload so the renderer can only reach declared channels. */
export const INVOKE_CHANNELS: InvokeChannel[] = [
  "auth:state",
  "auth:signInWithToken",
  "auth:deviceStart",
  "auth:deviceCancel",
  "auth:deviceAvailable",
  "auth:signOut",
  "github:listRepos",
  "github:createRepo",
  "github:openInBrowser",
  "vault:config",
  "vault:setup",
  "vault:chooseFolder",
  "vault:defaultPath",
  "vault:rescan",
  "vault:index",
  "vault:updateConfig",
  "vault:disconnect",
  "vault:revealInFinder",
  "doc:read",
  "doc:save",
  "doc:trash",
  "doc:setStarred",
  "doc:history",
  "doc:atCommit",
  "doc:restore",
  "doc:pathPreview",
  "project:rename",
  "project:list",
  "sync:status",
  "sync:pushNow",
  "sync:pull",
  "sync:resolveConflict",
  "views:list",
  "views:save",
  "views:delete",
  "templates:list",
  "search:query",
  "capture:readClipboard",
  "capture:hide",
  "capture:openEditor",
  "window:openMain",
  "window:openEditor",
  "app:version",
  "app:platform",
];

export const EVENT_CHANNELS: EventChannel[] = [
  "index:changed",
  "index:progress",
  "sync:status",
  "auth:state",
  "auth:deviceStatus",
  "capture:shown",
  "editor:open",
  "shortcut",
  "navigate",
];
